source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.2.1'
gem 'middleman-gh-pages', '~> 0.0.3'
gem 'middleman-syntax', '~> 3.0'
gem 'middleman-autoprefixer', '~> 2.4.4'
gem 'sprockets', '~> 3.7', '>= 3.7.2'
gem 'rouge', '~> 2.0'
gem 'redcarpet', '~> 3.3.1'

gem 'rake', '~> 10.4.2'
gem "rack", ">= 2.0.6"
gem 'therubyracer', '~> 0.12.1', platforms: :ruby

# In order to remove deprecation warning with the solution of
# You can use the sass-convert command to automatically fix most cases.
git 'https://github.com/ably-forks/compass', branch: 'sass-deprecation-warning-fix' do
  gem 'compass-core'
end
