source "https://rubygems.org"

gem 'nokogiri', '1.8.4'
gem "atomic", '= 1.0.1'
gem "json", "1.8.6"
gem 'sinatra', '~> 2.0', '>= 2.0.4', :require => false
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.4', :require => false
gem "activesupport", "5.0.1"
gem "fog-aws", "2.0.0", :require => false
gem 'multi_json', '~> 1.13.1'
gem "mime-types", "3.1"
gem "i18n", "0.9.1"
gem "rack", ">= 2.0.6"
